version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=neptuno
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docs/neptuno.sql:/docker-entrypoint-initdb.d/neptuno.sql